from pathlib import Path

# Base paths
BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"

# Input/Output paths
INPUT_PATH = DATA_DIR / "input"
OUTPUT_PATH = DATA_DIR / "output"

# File patterns
INPUT_FILE_PATTERN = "*.docx"

# LLM settings
USE_OPENAI = True
MAX_TOKENS = 128000
OPENAI_MODEL = "gpt-4o-2024-11-20"  
GROQ_MODEL = "llama-3.1-70b-versatile"

# Output formatting
HEADER = "*Amplifon CoE - Alkemy - onboarding sessions*\n\n---\n\n"
DISCLAIMER = "\n\n---\n\n DISCLAIMER: *This text was generated by an AI language model and may contain errors or inaccuracies.*"
